/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  ApiAuthenticationLoginRequest,
  apiAuthenticationLoginRequestSchema,
} from '../models/apiAuthenticationLoginRequest';
import {
  ApiAuthenticationRegisterRequest,
  apiAuthenticationRegisterRequestSchema,
} from '../models/apiAuthenticationRegisterRequest';
import { unknown } from '../schema';
import { BaseController } from './baseController';

export class AuthenticationController extends BaseController {
  /**
   * @param body
   * @return Response from the API call
   */
  async apiAuthenticationLogin(
    body: ApiAuthenticationLoginRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Authentication/Login');
    const mapped = req.prepareArgs({
      body: [body, apiAuthenticationLoginRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiAuthenticationRegister(
    body: ApiAuthenticationRegisterRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Authentication/Register');
    const mapped = req.prepareArgs({
      body: [body, apiAuthenticationRegisterRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(unknown(), requestOptions);
  }
}
