/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  ApiCountryAddCountryRequest,
  apiCountryAddCountryRequestSchema,
} from '../models/apiCountryAddCountryRequest';
import {
  ApiCountryDeleteCountryRequest,
  apiCountryDeleteCountryRequestSchema,
} from '../models/apiCountryDeleteCountryRequest';
import {
  ApiCountryUpdateCountryRequest,
  apiCountryUpdateCountryRequestSchema,
} from '../models/apiCountryUpdateCountryRequest';
import { unknown } from '../schema';
import { BaseController } from './baseController';

export class CountryController extends BaseController {
  /**
   * @return Response from the API call
   */
  async apiCountryId(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/Country/3691');
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async apiCountry(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/Country');
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiCountryAddCountry(
    body: ApiCountryAddCountryRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Country/AddCountry');
    const mapped = req.prepareArgs({
      body: [body, apiCountryAddCountryRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiCountryUpdateCountry(
    body: ApiCountryUpdateCountryRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Country/UpdateCountry');
    const mapped = req.prepareArgs({
      body: [body, apiCountryUpdateCountryRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiCountryDeleteCountry(
    body: ApiCountryDeleteCountryRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Country/DeleteCountry');
    const mapped = req.prepareArgs({
      body: [body, apiCountryDeleteCountryRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }
}
