/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  ApiPermissionAddPermissionRequest,
  apiPermissionAddPermissionRequestSchema,
} from '../models/apiPermissionAddPermissionRequest';
import { string, unknown } from '../schema';
import { BaseController } from './baseController';

export class PermissionController extends BaseController {
  /**
   * @return Response from the API call
   */
  async apiPermissionId(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/Permission/3691');
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async apiPermission(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/Permission');
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiPermissionAddPermission(
    body: ApiPermissionAddPermissionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Permission/AddPermission');
    const mapped = req.prepareArgs({
      body: [body, apiPermissionAddPermissionRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiPermissionUpdatePermissionId(
    body: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Permission/UpdatePermission/3691');
    const mapped = req.prepareArgs({ body: [body, string()] });
    req.header('Content-Type', 'application/json');
    req.text(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async apiPermissionDeletePermissionId(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Permission/DeletePermission/3691');
    return req.callAsJson(unknown(), requestOptions);
  }
}
