/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  ApiRegionAddRegionRequest,
  apiRegionAddRegionRequestSchema,
} from '../models/apiRegionAddRegionRequest';
import {
  ApiRegionDeleteRegionRequest,
  apiRegionDeleteRegionRequestSchema,
} from '../models/apiRegionDeleteRegionRequest';
import {
  ApiRegionUpdateRegionRequest,
  apiRegionUpdateRegionRequestSchema,
} from '../models/apiRegionUpdateRegionRequest';
import { unknown } from '../schema';
import { BaseController } from './baseController';

export class RegionController extends BaseController {
  /**
   * @return Response from the API call
   */
  async apiRegionId(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/Region/3691');
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async apiRegion(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/Region');
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiRegionAddRegion(
    body: ApiRegionAddRegionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Region/AddRegion');
    const mapped = req.prepareArgs({
      body: [body, apiRegionAddRegionRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiRegionUpdateRegion(
    body: ApiRegionUpdateRegionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Region/UpdateRegion');
    const mapped = req.prepareArgs({
      body: [body, apiRegionUpdateRegionRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiRegionDeleteRegion(
    body: ApiRegionDeleteRegionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/Region/DeleteRegion');
    const mapped = req.prepareArgs({
      body: [body, apiRegionDeleteRegionRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }
}
