/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  ApiWineLabelDeleteWineLabelRequest,
  apiWineLabelDeleteWineLabelRequestSchema,
} from '../models/apiWineLabelDeleteWineLabelRequest';
import {
  ApiWineLabelUpdateWineLabelRequest,
  apiWineLabelUpdateWineLabelRequestSchema,
} from '../models/apiWineLabelUpdateWineLabelRequest';
import {
  ApiWineLabelWineLabelRequest,
  apiWineLabelWineLabelRequestSchema,
} from '../models/apiWineLabelWineLabelRequest';
import { unknown } from '../schema';
import { BaseController } from './baseController';

export class WineLabelController extends BaseController {
  /**
   * @return Response from the API call
   */
  async apiWineLabelId(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/WineLabel/3691');
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async apiWineLabel(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/WineLabel');
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiWineLabelDeleteWineLabel(
    body: ApiWineLabelDeleteWineLabelRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/WineLabel/DeleteWineLabel/1');
    const mapped = req.prepareArgs({
      body: [body, apiWineLabelDeleteWineLabelRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiWineLabelWineLabel(
    body: ApiWineLabelWineLabelRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/WineLabel/WineLabel');
    const mapped = req.prepareArgs({
      body: [body, apiWineLabelWineLabelRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiWineLabelUpdateWineLabel(
    body: ApiWineLabelUpdateWineLabelRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/WineLabel/UpdateWineLabel');
    const mapped = req.prepareArgs({
      body: [body, apiWineLabelUpdateWineLabelRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(unknown(), requestOptions);
  }
}
