/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string, unknown } from '../schema';

export interface ApiAuthenticationRegisterRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  role?: unknown;
}

export const apiAuthenticationRegisterRequestSchema: Schema<ApiAuthenticationRegisterRequest> = object(
  {
    firstName: ['firstName', string()],
    lastName: ['lastName', string()],
    email: ['email', string()],
    password: ['password', string()],
    role: ['role', unknown()],
  }
);
