/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  number,
  object,
  Schema,
  string,
  unknown,
} from '../schema';

export interface ApiBottleUpdateBottleRequest {
  id: number;
  fullName: string;
  description: string;
  volume: number;
  picture: string;
  yearProduced: number;
  alcoholPercentage: number;
  supplierPrice: number;
  customerPrice: number;
  wineType: string;
  thresholdToOrder: string | null;
  quantityMinimumToOrder: string | null;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
  vat: string | null;
  vatId: string | null;
  producerId: number;
  wineLabelId: string | null;
  bottleStorageLocations: string[];
  supplierOrderLines: string | null;
  bottleGrapes: string[];
  bottleSuppliers: string[];
  producer?: unknown;
  wineLabel: string | null;
}

export const apiBottleUpdateBottleRequestSchema: Schema<ApiBottleUpdateBottleRequest> = object(
  {
    id: ['id', number()],
    fullName: ['fullName', string()],
    description: ['description', string()],
    volume: ['volume', number()],
    picture: ['picture', string()],
    yearProduced: ['yearProduced', number()],
    alcoholPercentage: ['alcoholPercentage', number()],
    supplierPrice: ['supplierPrice', number()],
    customerPrice: ['customerPrice', number()],
    wineType: ['wineType', string()],
    thresholdToOrder: ['thresholdToOrder', nullable(string())],
    quantityMinimumToOrder: ['quantityMinimumToOrder', nullable(string())],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', string()],
    createdBy: ['createdBy', string()],
    updatedBy: ['updatedBy', string()],
    vat: ['vat', nullable(string())],
    vatId: ['vatId', nullable(string())],
    producerId: ['producerId', number()],
    wineLabelId: ['wineLabelId', nullable(string())],
    bottleStorageLocations: ['bottleStorageLocations', array(string())],
    supplierOrderLines: ['supplierOrderLines', nullable(string())],
    bottleGrapes: ['bottleGrapes', array(string())],
    bottleSuppliers: ['bottleSuppliers', array(string())],
    producer: ['producer', unknown()],
    wineLabel: ['wineLabel', nullable(string())],
  }
);
