/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema';

export interface ApiCityAddCityRequest {
  name: string;
  zipCode: number;
  createdBy: string | null;
  updatedBy: string | null;
  countryId: string | null;
  country: string | null;
  addresses: string | null;
}

export const apiCityAddCityRequestSchema: Schema<ApiCityAddCityRequest> = object(
  {
    name: ['name', string()],
    zipCode: ['zipCode', number()],
    createdBy: ['createdBy', nullable(string())],
    updatedBy: ['updatedBy', nullable(string())],
    countryId: ['countryId', nullable(string())],
    country: ['country', nullable(string())],
    addresses: ['addresses', nullable(string())],
  }
);
