/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema';

export interface ApiCityUpdateCityRequest {
  id: number;
  name: string;
  zipCode: number;
  createdAt: string;
  updatedAt: string;
  createdBy: string | null;
  updatedBy: string | null;
  countryId: string | null;
  country: string | null;
  addresses: string | null;
}

export const apiCityUpdateCityRequestSchema: Schema<ApiCityUpdateCityRequest> = object(
  {
    id: ['id', number()],
    name: ['name', string()],
    zipCode: ['zipCode', number()],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', string()],
    createdBy: ['createdBy', nullable(string())],
    updatedBy: ['updatedBy', nullable(string())],
    countryId: ['countryId', nullable(string())],
    country: ['country', nullable(string())],
    addresses: ['addresses', nullable(string())],
  }
);
