/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema';

export interface ApiGrapeDeleteGrapeRequest {
  id: number;
  grapeType: string | null;
  createdAt: string;
  updatedAt: string;
  createdBy: string | null;
  updatedBy: string | null;
  bottleGrapes: string | null;
}

export const apiGrapeDeleteGrapeRequestSchema: Schema<ApiGrapeDeleteGrapeRequest> = object(
  {
    id: ['id', number()],
    grapeType: ['grapeType', nullable(string())],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', string()],
    createdBy: ['createdBy', nullable(string())],
    updatedBy: ['updatedBy', nullable(string())],
    bottleGrapes: ['bottleGrapes', nullable(string())],
  }
);
