/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface ApiGrapeAddGrapeRequest {
  grapeType: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string | null;
  bottleGrapes: string | null;
}

export const apiGrapeAddGrapeRequestSchema: Schema<ApiGrapeAddGrapeRequest> = object(
  {
    grapeType: ['grapeType', string()],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', string()],
    createdBy: ['createdBy', string()],
    updatedBy: ['updatedBy', nullable(string())],
    bottleGrapes: ['bottleGrapes', nullable(string())],
  }
);
