/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface ApiPermissionAddPermissionRequest {
  name: string;
  createdAt: string;
  updatedAt: string;
  permissionRoles: string | null;
}

export const apiPermissionAddPermissionRequestSchema: Schema<ApiPermissionAddPermissionRequest> = object(
  {
    name: ['name', string()],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', string()],
    permissionRoles: ['permissionRoles', nullable(string())],
  }
);
