/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface ApiProducerAddProducerRequest {
  name: string;
  details: string;
  createdAt: string;
  updatedAt: string | null;
  createdBy: string;
  updatedBy: string;
  bottles: string | null;
  region: string | null;
  address: string | null;
}

export const apiProducerAddProducerRequestSchema: Schema<ApiProducerAddProducerRequest> = object(
  {
    name: ['name', string()],
    details: ['details', string()],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', nullable(string())],
    createdBy: ['createdBy', string()],
    updatedBy: ['updatedBy', string()],
    bottles: ['bottles', nullable(string())],
    region: ['region', nullable(string())],
    address: ['address', nullable(string())],
  }
);
