/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema';

export interface ApiRoleUpdateRoleRequest {
  id: number;
  name: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string | null;
  updatedBy: string | null;
  permissionRoles: string | null;
  users: string | null;
}

export const apiRoleUpdateRoleRequestSchema: Schema<ApiRoleUpdateRoleRequest> = object(
  {
    id: ['id', number()],
    name: ['name', string()],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', string()],
    createdBy: ['createdBy', nullable(string())],
    updatedBy: ['updatedBy', nullable(string())],
    permissionRoles: ['permissionRoles', nullable(string())],
    users: ['users', nullable(string())],
  }
);
