/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface ApiRegionAddRegionRequest {
  name: string;
  createdAt: string;
  updatedAt: string | null;
  createdBy: string;
  updatedBy: string;
  countryId: string | null;
  producers: string | null;
  country: string | null;
}

export const apiRegionAddRegionRequestSchema: Schema<ApiRegionAddRegionRequest> = object(
  {
    name: ['name', string()],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', nullable(string())],
    createdBy: ['createdBy', string()],
    updatedBy: ['updatedBy', string()],
    countryId: ['countryId', nullable(string())],
    producers: ['producers', nullable(string())],
    country: ['country', nullable(string())],
  }
);
