/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface ApiStorageLocationAddStorageLocationRequest {
  name: string;
  createdAt: string;
  updatedAt: string | null;
  createdBy: string;
  updatedBy: string;
  bottleStorageLocations: string | null;
  customerOrderLineStorageLocations: string | null;
}

export const apiStorageLocationAddStorageLocationRequestSchema: Schema<ApiStorageLocationAddStorageLocationRequest> = object(
  {
    name: ['name', string()],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', nullable(string())],
    createdBy: ['createdBy', string()],
    updatedBy: ['updatedBy', string()],
    bottleStorageLocations: ['bottleStorageLocations', nullable(string())],
    customerOrderLineStorageLocations: [
      'customerOrderLineStorageLocations',
      nullable(string()),
    ],
  }
);
