/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface ApiSupplierAddSupplierRequest {
  name: string;
  details: string;
  email: string;
  createdAt: string;
  updatedAt: string | null;
  createdBy: string;
  updatedBy: string;
  bottleSuppliers: string | null;
  address: string | null;
}

export const apiSupplierAddSupplierRequestSchema: Schema<ApiSupplierAddSupplierRequest> = object(
  {
    name: ['name', string()],
    details: ['details', string()],
    email: ['email', string()],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', nullable(string())],
    createdBy: ['createdBy', string()],
    updatedBy: ['updatedBy', string()],
    bottleSuppliers: ['bottleSuppliers', nullable(string())],
    address: ['address', nullable(string())],
  }
);
