/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string, unknown } from '../schema';

export interface ApiUserUpdateUserRequest {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string | null;
  updatedBy: string | null;
  refreshToken: string | null;
  refreshTokenExpiryTime: string | null;
  addresses: string | null;
  role?: unknown;
}

export const apiUserUpdateUserRequestSchema: Schema<ApiUserUpdateUserRequest> = object(
  {
    id: ['id', number()],
    firstName: ['firstName', string()],
    lastName: ['lastName', string()],
    email: ['email', string()],
    password: ['password', string()],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', string()],
    createdBy: ['createdBy', nullable(string())],
    updatedBy: ['updatedBy', nullable(string())],
    refreshToken: ['refreshToken', nullable(string())],
    refreshTokenExpiryTime: ['refreshTokenExpiryTime', nullable(string())],
    addresses: ['addresses', nullable(string())],
    role: ['role', unknown()],
  }
);
