/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema';

export interface ApiWineLabelUpdateWineLabelRequest {
  id: number;
  label: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string | null;
  updatedBy: string | null;
  bottles: string | null;
}

export const apiWineLabelUpdateWineLabelRequestSchema: Schema<ApiWineLabelUpdateWineLabelRequest> = object(
  {
    id: ['id', number()],
    label: ['label', string()],
    createdAt: ['createdAt', string()],
    updatedAt: ['updatedAt', string()],
    createdBy: ['createdBy', nullable(string())],
    updatedBy: ['updatedBy', nullable(string())],
    bottles: ['bottles', nullable(string())],
  }
);
