/**
 * API_NEGOSUD.yamlLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { HttpClientOptions } from './core';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  environment: Environment;
  scheme: string;
  host: string;
  baseUrl: string;
  accessToken: string;
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
}

/** Environments available for API */
export enum Environment {
  Base = 'Base',
  OpenAPIEnvNegosudProd = 'OpenAPI env negosud prod',
  NewEnvironment = 'New Environment',
}
